In [1]:
import numpy as np
import random as rd

p1 = np.array((0,0))
p2 = np.array((0,0))
p3 = np.array((0,0))

n_part = 100000
n_door = 3
n_choice = 2
n_goat = n_door - n_choice

data = np.zeros((1,4))

for i in range (1,n_part+1):
    choice = rd.randint(0,n_door-1)
    p1[0] = choice
    p2[0] = choice
    car = rd.randint(0,n_door-1)

    check = 0
    door_op = np.array([])
    while check<n_goat:
        remove = rd.randint(0,n_door-1)
        while remove==choice or remove in door_op or remove==car:
            remove = rd.randint(0,n_door-1)
        door_op = np.append(door_op, remove)
        check +=1
           
    while choice==p1[0] or p1[0] in door_op:
        p1[0] = rd.randint(0,n_door-1)

    p3[0] = rd.randint(0,n_door-1) 
    while p3[0] in door_op:
        p3[0] = rd.randint(0,n_door-1)
        
    if p1[0] == car:
        p1[1] += 1
    if p2[0] == car:
        p2[1] += 1
    if p3[0] == car:
        p3[1] += 1
        
    if i==100:
        data[0,0] = i
        data[0,1] = p1[1]/i
        data[0,2] = p2[1]/i
        data[0,3] = p3[1]/i
        
    if i%100 == 0 and i>100:
        data = np.append(data,[[i, p1[1]/i, p2[1]/i, p3[1]/i]], axis=0)
        
print(data)
    
#print("Su ", n_part, " partite \np1 ha vinto:",p1[1], "volte \np2 ha vinto:",p2[1], "volte \np3 ha vinto:",p3[1], "volte")




[[1.00000000e+02 6.40000000e-01 3.60000000e-01 4.90000000e-01]
 [2.00000000e+02 6.50000000e-01 3.50000000e-01 4.45000000e-01]
 [3.00000000e+02 6.70000000e-01 3.30000000e-01 4.63333333e-01]
 ...
 [9.98000000e+04 6.66763527e-01 3.33236473e-01 5.00000000e-01]
 [9.99000000e+04 6.66776777e-01 3.33223223e-01 4.99949950e-01]
 [1.00000000e+05 6.66800000e-01 3.33200000e-01 4.99860000e-01]]
