In [1]:
import numpy as np
import random as rd

p1 = np.array((0,0))
p2 = np.array((0,0))
p3 = np.array((0,0))

n_part = 100000
n_door = 10
n_choice = 4
n_op_door = n_door - n_choice

data = np.zeros((1,4))

for i in range (1,n_part+1):
    choice = rd.randint(0,n_door-1)
    p1[0] = choice
    p2[0] = choice
    car = rd.randint(0,n_door-1)

    doors_to_open = np.array([])
    doors_to_choose = np.array([])
    for n in range (0,n_door):
        if n!= choice:
            doors_to_choose = np.append(doors_to_choose,n)
        if n!=choice and n!=car:
            doors_to_open = np.append(doors_to_open,n)
            
    doors_to_open = doors_to_open.astype(int)
    doors_to_choose = doors_to_choose.astype(int)
    for n in range (0,n_op_door):
        remove = rd.choice(doors_to_open)
        pos1 = np.searchsorted(doors_to_open, remove)
        pos2 = np.searchsorted(doors_to_choose, remove)
        doors_to_open = np.delete(doors_to_open, pos1)
        doors_to_choose = np.delete(doors_to_choose, pos2)

    p1[0] = rd.choice(doors_to_choose)

    doors_to_choose = np.append(doors_to_choose, choice)
    p3[0] = rd.choice(doors_to_choose)
        
    if p1[0] == car:
        p1[1] += 1
    if p2[0] == car:
        p2[1] += 1
    if p3[0] == car:
        p3[1] += 1
        
    if i==100:
        data[0,0] = i
        data[0,1] = p1[1]/i
        data[0,2] = p2[1]/i
        data[0,3] = p3[1]/i
        
    if i%100 == 0 and i>100:
        data = np.append(data,[[i, p1[1]/i, p2[1]/i, p3[1]/i]], axis=0)
    
print(data)   


[[1.00000000e+02 3.00000000e-01 1.30000000e-01 2.30000000e-01]
 [2.00000000e+02 2.55000000e-01 1.25000000e-01 2.30000000e-01]
 [3.00000000e+02 2.70000000e-01 1.23333333e-01 2.36666667e-01]
 ...
 [9.98000000e+04 3.00721443e-01 9.88076152e-02 2.51212425e-01]
 [9.99000000e+04 3.00750751e-01 9.87987988e-02 2.51191191e-01]
 [1.00000000e+05 3.00780000e-01 9.88100000e-02 2.51240000e-01]]
