In [23]:
import numpy as np
import random as rd

p1 = np.array((0,0))
p2 = np.array((0,0))
p3 = np.array((0,0))

n_part = 10000
n_door = 3
n_choice = 2
n_goat = n_door - n_choice

data = np.zeros((1,4))

for i in range (1,n_part+1):
    choice = rd.randint(0,n_door-1)
    p1[0] = choice
    p2[0] = choice
    car = rd.randint(0,n_door-1)

    check = 0
    door_op = np.array([])
    while check<n_goat:
        remove = rd.randint(0,n_door-1)
        while remove==choice or remove in door_op or remove==car:
            remove = rd.randint(0,n_door-1)
        door_op = np.append(door_op, remove)
        check +=1
           
    while choice==p1[0] or p1[0] in door_op:
        p1[0] = rd.randint(0,n_door-1)

    p3[0] = rd.randint(0,n_door-1) 
    while p3[0] in door_op:
        p3[0] = rd.randint(0,n_door-1)
        
    if p1[0] == car:
        p1[1] += 1
    if p2[0] == car:
        p2[1] += 1
    if p3[0] == car:
        p3[1] += 1
        
    if i==100:
        data[0,0] = i
        data[0,1] = p1[1]/i
        data[0,2] = p2[1]/i
        data[0,3] = p3[1]/i
        
    if i%100 == 0 and i>100:
        data = np.append(data,[[i, p1[1]/i, p2[1]/i, p3[1]/i]], axis=0)
        
print(data)
    
#print("Su ", n_part, " partite \np1 ha vinto:",p1[1], "volte \np2 ha vinto:",p2[1], "volte \np3 ha vinto:",p3[1], "volte")




[[1.00000000e+02 8.00000000e-01 2.00000000e-01 4.50000000e-01]
 [2.00000000e+02 7.70000000e-01 2.30000000e-01 4.65000000e-01]
 [3.00000000e+02 7.50000000e-01 2.50000000e-01 5.00000000e-01]
 [4.00000000e+02 7.22500000e-01 2.77500000e-01 5.05000000e-01]
 [5.00000000e+02 7.16000000e-01 2.84000000e-01 4.94000000e-01]
 [6.00000000e+02 7.06666667e-01 2.93333333e-01 5.11666667e-01]
 [7.00000000e+02 7.01428571e-01 2.98571429e-01 5.01428571e-01]
 [8.00000000e+02 6.97500000e-01 3.02500000e-01 4.85000000e-01]
 [9.00000000e+02 6.94444444e-01 3.05555556e-01 4.81111111e-01]
 [1.00000000e+03 6.94000000e-01 3.06000000e-01 4.85000000e-01]
 [1.10000000e+03 6.93636364e-01 3.06363636e-01 4.83636364e-01]
 [1.20000000e+03 6.89166667e-01 3.10833333e-01 4.81666667e-01]
 [1.30000000e+03 6.84615385e-01 3.15384615e-01 4.84615385e-01]
 [1.40000000e+03 6.85000000e-01 3.15000000e-01 4.87857143e-01]
 [1.50000000e+03 6.86666667e-01 3.13333333e-01 4.86000000e-01]
 [1.60000000e+03 6.83750000e-01 3.16250000e-01 4.843750